SIZE = 2;
CELL_SIZE = 20;

HEIGHT = 2;
WALL_HEIGHT = 4;
GROUND_HEIGHT = HEIGHT * 2.5;
MARGIN = CELL_SIZE / 10;
OFFSET = 0.5;
CLEARANCE = 0.3;

HOUSE_WIDTH = CELL_SIZE - CLEARANCE;
HOUSE_DEPTH = CELL_SIZE * 2/3 - CLEARANCE;
HOUSE_HEIGHT = CELL_SIZE  * 2/3;

$fn = 20;